logging:
  level:
    com:
      zaxxer:
        hikari: DEBUG
server:
  port: 8083
spring:
  application:
    name: fund-transfer
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      idle-timeout: 60000
      maximum-pool-size: 10
      minimum-idle: 5
    password: my_bank_user
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: my_bank_user
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        ddl-auto: update
        dialect: org.hibernate.dialect.OracleDialect
        format_sql: true
        generate_statistics: true
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ # URL for the Eureka server
    register-with-eureka: true # Registers this service with Eureka
    fetch-registry: true       # Fetches the service registry from Eureka
