logging:
  level:
    com.zaxxer.hikari: DEBUG # Enables detailed logging for HikariCP

server:
  port: 8082

spring:
  application:
    name: account-service
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      idle-timeout: 60000
      maximum-pool-size: 10
      minimum-idle: 5
    password: my_bank_user
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: my_bank_user
  jpa:
    hibernate:
      ddl-auto: update # Controls the schema generation strategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect # Use Oracle-specific dialect
        format_sql: true # Formats SQL output for better readability
        generate_statistics: true # Enables Hibernate statistics for performance monitoring
    show-sql: true # Displays SQL queries in logs

user:
  service:
    url: http://localhost:8081 # URL for the user-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ # URL for the Eureka server
    register-with-eureka: true # Registers this service with Eureka
    fetch-registry: true       # Fetches the service registry from Eureka
